import type { DivineAction } from "../types/game";

export const divineActions: DivineAction[] = [
  {
    id: "whisper",
    name: "เสียงกระซิบ",
    nameTh: "เสียงกระซิบ",
    description: "เทพกระซิบแนวทางให้ผู้หลงทาง เพิ่มโอกาสตัดสินใจถูกต้อง แต่อาจทำให้เขาเริ่มพึ่งพาเสียงของเทพมากขึ้น",
    descriptionTh: "เทพกระซิบแนวทางให้ผู้หลงทาง เพิ่มโอกาสตัดสินใจถูกต้อง แต่อาจทำให้เขาเริ่มพึ่งพาเสียงของเทพมากขึ้น",
    chancePreviewTh: "ปานกลาง",
    benefitPreviewTh: "เพิ่มโอกาสตัดสินใจถูกต้อง",
    riskPreviewTh: "ผู้หลงทางอาจพึ่งพาเสียงของเทพมากขึ้น",
    possibleChangesTh: ["ศรัทธา +0 ถึง +1", "การพึ่งพาเทพ +1"],
    successChanceModifier: 0.08,
    preferredContexts: ["puzzle", "moral", "npc", "decision", "choice"],
    scoreModifier: 8,
    relationshipChanges: { dependency: 1 },
    survivalChanges: { hope: 2 },
  },
  {
    id: "omen",
    name: "ลางบอกเหตุ",
    nameTh: "ลางบอกเหตุ",
    description: "เทพส่งสัญญาณเตือนถึงอันตราย เพิ่มโอกาสหลีกเลี่ยงความเสี่ยง แต่อาจทำให้จิตใจหวาดระแวง",
    descriptionTh: "เทพส่งสัญญาณเตือนถึงอันตราย เพิ่มโอกาสหลีกเลี่ยงความเสี่ยง แต่อาจทำให้จิตใจหวาดระแวง",
    chancePreviewTh: "ปานกลาง-สูง เมื่อมีอันตรายหรือกับดัก",
    benefitPreviewTh: "ลดโอกาสบาดเจ็บหรือพลาดกับดัก",
    riskPreviewTh: "ขวัญกำลังใจอาจลดจากความหวาดระแวง",
    possibleChangesTh: ["ขวัญกำลังใจ -0 ถึง -3", "อาการบาดเจ็บมีโอกาสลดลง"],
    successChanceModifier: 0.06,
    preferredContexts: ["survival", "combat", "boss", "darkness", "fear", "danger"],
    scoreModifier: 6,
    relationshipChanges: {},
    survivalChanges: { morale: -2 },
  },
  {
    id: "blessing",
    name: "พรแห่งเทพ",
    nameTh: "พรแห่งเทพ",
    description: "เทพมอบพลังชั่วคราวให้ผู้หลงทาง ช่วยให้ผ่านสถานการณ์ยากลำบาก แต่เพิ่มการพึ่งพาเทพ",
    descriptionTh: "เทพมอบพลังชั่วคราวให้ผู้หลงทาง ช่วยให้ผ่านสถานการณ์ยากลำบาก แต่เพิ่มการพึ่งพาเทพ",
    chancePreviewTh: "สูง",
    benefitPreviewTh: "ได้โบนัสมากที่สุด เหมาะกับสถานการณ์วิกฤต",
    riskPreviewTh: "การพึ่งพาเทพเพิ่มขึ้นชัดเจน",
    possibleChangesTh: ["ศรัทธา +1 ถึง +2", "การพึ่งพาเทพ +2"],
    successChanceModifier: 0.16,
    preferredContexts: ["combat", "boss", "survival", "crisis"],
    scoreModifier: 14,
    relationshipChanges: { faith: 1, dependency: 2 },
    survivalChanges: { hope: 3 },
  },
  {
    id: "silence",
    name: "ความเงียบ",
    nameTh: "ความเงียบ",
    description: "เทพไม่แทรกแซง ปล่อยให้ผู้หลงทางตัดสินใจด้วยตนเอง เสี่ยงกว่า แต่ช่วยให้เขาเติบโต",
    descriptionTh: "เทพไม่แทรกแซง ปล่อยให้ผู้หลงทางตัดสินใจด้วยตนเอง เสี่ยงกว่า แต่ช่วยให้เขาเติบโต",
    chancePreviewTh: "ต่ำ-ปานกลาง",
    benefitPreviewTh: "หากรอดได้ การยืนหยัดด้วยตนเองจะเพิ่มมาก",
    riskPreviewTh: "ไม่มีโบนัสช่วยเหลือ และอาจบาดเจ็บหากล้มเหลว",
    possibleChangesTh: ["การยืนหยัดด้วยตนเอง +1 ถึง +3 เมื่อสำเร็จ"],
    successChanceModifier: 0,
    preferredContexts: ["growth", "choice", "moral", "darkness"],
    scoreModifier: 0,
    relationshipChanges: { dependency: -1 },
    survivalChanges: {},
  },
];
